# Generated by Django 2.2.7 on 2019-11-10 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('numbering', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('pdf', models.FileField(upload_to='books/')),
            ],
        ),
    ]
